export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const STATUS_START = 'STATUS_START';
export const STATUS_FAIL = 'STATUS_FAIL';
export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS';
export const FETCH_USER_STATUSES_SUCCESS = 'FETCH_USER_SUCCESS';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';

export const USER_START = 'USER_START';
export const USER_FAIL = 'USER_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const PATCH_USER_SUCCESS = 'PATCH_USER_SUCCESS';
export const PUT_ADD_USER_SUCCESS = 'PUT_ADD_USER_SUCCESS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';