export const POST_STATUS_START = 'POST_STATUS_START';
export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS';
export const POST_STATUS_FAIL = 'POST_STATUS_FAIL';
export const POST_INIT = 'PURCHASE_INIT';

export const FETCH_USER_STATUSES_START = 'FETCH_USER_STATUSES_START';
export const FETCH_USER_STATUSES_SUCCESS = 'FETCH_USER_STATUSES_SUCCESS';
export const FETCH_USER_STATUSES_FAIL = 'FETCH_USER_STATUSES_FAIL';

export const DELETE_STATUS_START = 'DELETE_STATUS_START';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAIL = 'DELETE_STATUS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_LOGOUT = 'FETCH_USERS_LOGOUT';
export const PATCH_WALL_SUCCESS = 'PATCH_WALL_SUCCESS';
export const PATCH_WALL_FAIL = 'PATCH_WALL_FAIL';

export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL";

export const USER_WALL_UPDATE = "USER_WALL_UPDATE";

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';