export const POST_STATUS_START = 'POST_STATUS_START';
export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS';
export const POST_STATUS_FAIL = 'POST_STATUS_FAIL';
export const POST_INIT = 'PURCHASE_INIT';

export const FETCHED_STATUSES_START = 'FETCHED_STATUSES_START';
export const FETCHED_STATUSES_SUCCESS = 'FETCHED_STATUSES_SUCCESS';
export const FETCHED_STATUSES_FAIL = 'FETCHED_STATUSES_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL";

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';